FROM mysql:8.0
ENV MYSQL_ROOT_PASSWORD=ExpenseApp@1
ADD script/*.sql /docker-entrypoint-initdb.d
   
    # MYSQL_DATABASE=transactions\
    # MYSQL_USER=ExpenseApp@1\
    # MYSQL_PASSWORD=ExpenseApp@1

